### PR TITLE
Some improvements

### PR DESCRIPTION
**Pull request by Yehonal**
* implemented "exclude" and "only" for attributes

* fixed allowNull bug on Input types

* Implemented custom Scalar types

* n:m relation now are fully supported

* id in input type can be nullable when autoincrement

* some code optimization

* allow graphql null when db default field value exists and not null enabled

* improved README

* implemented exclude/only for create/fetch/update

* implemented inputUpdateTypes (because edit mutations can't have NotNull fields otherwise you're forced to update all fields)

* exclude createdAt and updatedAt from graphql, they are handled by sequelize internally

* more flexible custom types option (with legacy support)

it also closes https://github.com/alirizwan/sequelize-graphql-schema/issues/5 and https://github.com/alirizwan/sequelize-graphql-schema/issues/7

### CODE REVIEW

**Comment by Yehonal** [comment]
i've made tons of updates these days,  i cannot split in various PR sorry but you can test it and see that it's fully working with full legacy support

The only missing thing is nested mutation

**Comment by alirizwan** [comment]
@Yehonal I had to revert it, this is not backward compatible or maybe update models in tests to reflect changes done in code. It's breaking previous versions.

**Comment by Yehonal** [comment]
@alirizwan we should only update the tests because n:m now uses the graphql-sequelize syntax (with edges and nodes), we can't keep the backward compatibility on it since it's a new syntax to support that feature.
About the other fixes, they should be backward compat.

**Comment by alirizwan** [comment]
I'll adjust test cases and update documentation with change log and publish it.

**Comment by alirizwan** [comment]
@Yehonal change line#749 to `let customField = customTypes[fieldReference.type] || getCustomType(model, fieldReference.type, customTypes, isInput, true);`

**Comment by alirizwan** [comment]
@Yehonal can you please raise your PR?

**Comment by Yehonal** [comment]
done

**Pull request merged**
