### PR TITLE
Feature/refactor

### PR DESCRIPTION
**Pull request by alirizwan**

### CODE REVIEW

**Comment by Yehonal** [comment]
@alirizwan are you working on integrating last features from develop-refactor branch? (such as subscriptions). Which is the current state?

**Comment by chirvo** [comment]
Wow, there's a lot of work made here. Can I ask why this pull request has not been applied? Thanks.

**Comment by alirizwan** [comment]
This is v1.0 in making. I’m just testing and trying to write enough test coverage for future versions.

Sent from my iPhone

On Feb 13, 2021, at 2:45 PM, Irving A. Bermúdez S. <notifications@github.com> wrote:

﻿

Wow, there's a lot of work made here. Can I ask why this pull request has not been applied? Thanks.

**Comment by alirizwan** [comment]
But this is published as graphcraft@beta

Sent from my iPhone

On Feb 13, 2021, at 2:45 PM, Irving A. Bermúdez S. <notifications@github.com> wrote:

﻿

Wow, there's a lot of work made here. Can I ask why this pull request has not been applied? Thanks.

**Comment by chirvo** [comment]
> 
> But this is published as graphcraft@beta


Thanks. If I see anything wrong while using it i let you guys know.

Cheers,

**Comment by luke-j** [comment]
Looks great. Would be nice to see this merged 👍

**Comment by jjcollinge** [comment]
@alirizwan do you intend to merge this and release a v1?

**Comment by alirizwan** [comment]
> h

Indeed. I will release this over the weekend. Just some final tests to be done.

**Pull request merged**
